var searchData=
[
  ['s_20in_20the_20docs_0',['What&apos;s in the docs',['../index.html#autotoc_md13',1,'']]],
  ['sequentialimpl_1',['SequentialImpl',['../classlmp_1_1nets_1_1SequentialImpl.html',1,'lmp::nets']]],
  ['shape_20manipulation_2',['Shape manipulation',['../using_tensor.html#autotoc_md42',1,'']]],
  ['sigmoidimpl_3',['SigmoidImpl',['../classlmp_1_1nets_1_1SigmoidImpl.html',1,'lmp::nets']]],
  ['sine_4',['Sine',['../structlmp_1_1autograd_1_1ops_1_1Sine.html',1,'lmp::autograd::ops']]],
  ['sinebackward_5',['SineBackward',['../structlmp_1_1autograd_1_1ops_1_1SineBackward.html',1,'lmp::autograd::ops']]],
  ['sinfn_6',['SinFn',['../structlmp_1_1tensor_1_1lazy_1_1SinFn.html',1,'lmp::tensor::lazy']]],
  ['sinfunctor_7',['SinFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1SinFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['softmaximpl_8',['SoftmaxImpl',['../classlmp_1_1nets_1_1SoftmaxImpl.html',1,'lmp::nets']]],
  ['solutions_9',['Common issues and solutions',['../getting_started.html#autotoc_md9',1,'']]],
  ['specific_20elements_10',['Working with specific elements',['../using_tensor.html#autotoc_md56',1,'']]],
  ['specific_20optimizations_11',['Device-specific optimizations',['../using_tensor.html#autotoc_md59',1,'']]],
  ['sqrtfn_12',['SqrtFn',['../structlmp_1_1tensor_1_1lazy_1_1SqrtFn.html',1,'lmp::tensor::lazy']]],
  ['sqrtfunctor_13',['SqrtFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1SqrtFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['squareroot_14',['SquareRoot',['../structlmp_1_1autograd_1_1ops_1_1SquareRoot.html',1,'lmp::autograd::ops']]],
  ['squarerootbackward_15',['SquareRootBackward',['../structlmp_1_1autograd_1_1ops_1_1SquareRootBackward.html',1,'lmp::autograd::ops']]],
  ['squeeze_16',['Squeeze',['../structlmp_1_1autograd_1_1ops_1_1Squeeze.html',1,'lmp::autograd::ops']]],
  ['squeezebackward_17',['SqueezeBackward',['../structlmp_1_1autograd_1_1ops_1_1SqueezeBackward.html',1,'lmp::autograd::ops']]],
  ['started_18',['started',['../index.html#autotoc_md11',1,'Getting started'],['../getting_started.html',1,'Getting Started']]],
  ['steps_19',['Next steps',['../using_tensor.html#autotoc_md62',1,'']]],
  ['storage_20',['Storage',['../classlmp_1_1tensor_1_1Storage.html',1,'lmp::tensor']]],
  ['storageimpl_21',['StorageImpl',['../classlmp_1_1tensor_1_1Storage_1_1StorageImpl.html',1,'lmp::tensor::Storage']]],
  ['structure_22',['Training loop structure',['../using_autograd.html#autotoc_md27',1,'']]],
  ['subfn_23',['SubFn',['../structlmp_1_1tensor_1_1lazy_1_1SubFn.html',1,'lmp::tensor::lazy']]],
  ['subfunctor_24',['SubFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1SubFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['subtract_25',['Subtract',['../structlmp_1_1autograd_1_1ops_1_1Subtract.html',1,'lmp::autograd::ops']]],
  ['subtractbackward_26',['SubtractBackward',['../structlmp_1_1autograd_1_1ops_1_1SubtractBackward.html',1,'lmp::autograd::ops']]],
  ['sumfunctor_27',['SumFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1SumFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['summation_28',['Summation',['../structlmp_1_1autograd_1_1ops_1_1Summation.html',1,'lmp::autograd::ops']]],
  ['summationbackward_29',['SummationBackward',['../structlmp_1_1autograd_1_1ops_1_1SummationBackward.html',1,'lmp::autograd::ops']]],
  ['support_30',['With CUDA support',['../getting_started.html#autotoc_md3',1,'']]]
];
