var searchData=
[
  ['captureguard_0',['CaptureGuard',['../classlmp_1_1tensor_1_1lazy_1_1CaptureGuard.html',1,'lmp::tensor::lazy']]],
  ['checking_20and_20manipulating_20gradients_1',['Checking and manipulating gradients',['../using_autograd.html#autotoc_md30',1,'']]],
  ['checkstream_2',['CheckStream',['../classlmp_1_1detail_1_1CheckStream.html',1,'lmp::detail']]],
  ['clamp_3',['Clamp',['../structlmp_1_1autograd_1_1ops_1_1Clamp.html',1,'lmp::autograd::ops']]],
  ['clampbackward_4',['ClampBackward',['../structlmp_1_1autograd_1_1ops_1_1ClampBackward.html',1,'lmp::autograd::ops']]],
  ['clampbackwardfunctor_5',['ClampBackwardFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1ClampBackwardFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['clampfn_6',['ClampFn',['../structlmp_1_1tensor_1_1lazy_1_1ClampFn.html',1,'lmp::tensor::lazy']]],
  ['clampfunctor_7',['ClampFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1ClampFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['common_20issues_20and_20solutions_8',['Common issues and solutions',['../getting_started.html#autotoc_md9',1,'']]],
  ['comparison_20operations_9',['Comparison operations',['../using_tensor.html#autotoc_md49',1,'']]],
  ['complete_20example_10',['Complete example',['../using_autograd.html#autotoc_md35',1,'']]],
  ['computation_20graph_11',['computation graph',['../using_autograd.html#autotoc_md22',1,'Operations and the computation graph'],['../using_autograd.html#autotoc_md28',1,'Understanding the computation graph']]],
  ['considerations_12',['considerations',['../using_tensor.html#autotoc_md58',1,'Performance considerations'],['../using_autograd.html#autotoc_md32',1,'Performance considerations']]],
  ['contributing_13',['Contributing',['../index.html#autotoc_md16',1,'']]],
  ['converting_20back_20to_20vectors_14',['Converting back to vectors',['../using_tensor.html#autotoc_md41',1,'']]],
  ['copies_15',['Views vs. copies',['../using_tensor.html#autotoc_md54',1,'']]],
  ['copy_16',['copy',['../classlmp_1_1tensor_1_1Tensor.html#aca131b4b0fb7585bc9a170e9e31afe62',1,'lmp::tensor::Tensor']]],
  ['copying_17',['copying',['../using_tensor.html#autotoc_md55',1,'Explicit copying'],['../using_tensor.html#autotoc_md53',1,'Memory management and copying']]],
  ['cosfn_18',['CosFn',['../structlmp_1_1tensor_1_1lazy_1_1CosFn.html',1,'lmp::tensor::lazy']]],
  ['cosfunctor_19',['CosFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1CosFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['cosine_20',['Cosine',['../structlmp_1_1autograd_1_1ops_1_1Cosine.html',1,'lmp::autograd::ops']]],
  ['cosinebackward_21',['CosineBackward',['../structlmp_1_1autograd_1_1ops_1_1CosineBackward.html',1,'lmp::autograd::ops']]],
  ['cpuoffsetutil_22',['CPUOffsetUtil',['../classlmp_1_1tensor_1_1detail_1_1cpu_1_1CPUOffsetUtil.html',1,'lmp::tensor::detail::cpu']]],
  ['creates_20gradient_20nodes_23',['What creates gradient nodes',['../using_autograd.html#autotoc_md23',1,'']]],
  ['creating_20tensors_24',['Creating tensors',['../using_tensor.html#autotoc_md36',1,'']]],
  ['creating_20variables_25',['Creating Variables',['../using_autograd.html#autotoc_md20',1,'']]],
  ['cuda_20support_26',['With CUDA support',['../getting_started.html#autotoc_md3',1,'']]]
];
