var searchData=
[
  ['makes_20lamp3_20different_0',['What makes Lamp3 different?',['../index.html#autotoc_md10',1,'']]],
  ['management_20and_20copying_1',['Memory management and copying',['../using_tensor.html#autotoc_md53',1,'']]],
  ['manipulating_20gradients_2',['Checking and manipulating gradients',['../using_autograd.html#autotoc_md30',1,'']]],
  ['manipulation_3',['Shape manipulation',['../using_tensor.html#autotoc_md42',1,'']]],
  ['math_5facc_5ft_4',['math_acc_t',['../namespacelmp_1_1tensor_1_1detail_1_1cpu.html#af639cd9973c9d533f1e46f4b25de056a',1,'lmp::tensor::detail::cpu']]],
  ['mathematical_20functions_5',['Mathematical functions',['../using_tensor.html#autotoc_md48',1,'']]],
  ['matrix_20operations_6',['Matrix operations',['../using_tensor.html#autotoc_md52',1,'']]],
  ['matrixmultiplication_7',['MatrixMultiplication',['../structlmp_1_1autograd_1_1ops_1_1MatrixMultiplication.html',1,'lmp::autograd::ops']]],
  ['matrixmultiplicationbackward_8',['MatrixMultiplicationBackward',['../structlmp_1_1autograd_1_1ops_1_1MatrixMultiplicationBackward.html',1,'lmp::autograd::ops']]],
  ['maxfunctor_9',['MaxFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1MaxFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['maximum_10',['Maximum',['../structlmp_1_1autograd_1_1ops_1_1Maximum.html',1,'lmp::autograd::ops']]],
  ['maximumbackward_11',['MaximumBackward',['../structlmp_1_1autograd_1_1ops_1_1MaximumBackward.html',1,'lmp::autograd::ops']]],
  ['memory_20layout_12',['Memory layout',['../using_tensor.html#autotoc_md60',1,'']]],
  ['memory_20management_20and_20copying_13',['Memory management and copying',['../using_tensor.html#autotoc_md53',1,'']]],
  ['memory_20usage_14',['Memory usage',['../using_autograd.html#autotoc_md33',1,'']]],
  ['might_20be_20perfect_20if_15',['This might be perfect if...',['../index.html#autotoc_md15',1,'']]],
  ['minfunctor_16',['MinFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1MinFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['minimum_17',['Minimum',['../structlmp_1_1autograd_1_1ops_1_1Minimum.html',1,'lmp::autograd::ops']]],
  ['minimumbackward_18',['MinimumBackward',['../structlmp_1_1autograd_1_1ops_1_1MinimumBackward.html',1,'lmp::autograd::ops']]],
  ['module_19',['Module',['../classlmp_1_1nets_1_1Module.html',1,'lmp::nets']]],
  ['moduleimpl_20',['ModuleImpl',['../classlmp_1_1nets_1_1ModuleImpl.html',1,'lmp::nets']]],
  ['mulfn_21',['MulFn',['../structlmp_1_1tensor_1_1lazy_1_1MulFn.html',1,'lmp::tensor::lazy']]],
  ['mulfunctor_22',['MulFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1MulFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['multiply_23',['Multiply',['../structlmp_1_1autograd_1_1ops_1_1Multiply.html',1,'lmp::autograd::ops']]],
  ['multiplybackward_24',['MultiplyBackward',['../structlmp_1_1autograd_1_1ops_1_1MultiplyBackward.html',1,'lmp::autograd::ops']]]
];
